### ISSUE TITLE
Save Game/Quit Function

### ISSUE THREAD

**Issue by dpijeira1** [fsu-fall2022-capstone/Project-Group-4#24]
Attach to pause menu a game save function and "quit to menu" function.

**Comment by SirTarragon** [comment]
Have you been developing this feature, @dpijeira1, or was it just an idea that you posted on the 17th of October?

**Comment by dpijeira1** [comment]
Just an idea leave it as low priority for now.

**Comment by SirTarragon** [comment]
Not enough time left to figure this out. Closing this.
